export const SET_USER_LOCATION = 'SET_USER_LOCATION';
export const GET_CARS = 'GET_CARS';
export const GET_CARS_FULLFILLED = 'GET_CARS_FULLFILLED';
export const START_POLLING_CARS = 'START_POLLING_CARS';
export const STOP_POLLING_CARS = 'STOP_POLLING_CARS';
